steps:
    # Build the container image
    -   name: 'gcr.io/cloud-builders/docker'
        args: [ 'build', '-t', 'asia.gcr.io/[FIREBASE_PROJECT_ID]/[API_NAME_IMAGES]', '.' ]
    # Push the container image to Container Registry
    -   name: 'gcr.io/cloud-builders/docker'
        args: [ 'push', 'asia.gcr.io/[FIREBASE_PROJECT_ID]/[API_NAME_IMAGES]' ]
    # Deploy container image to Cloud Run
    -   name: 'gcr.io/cloud-builders/gcloud'
        args:
            - 'run'
            - 'deploy'
            - '[API_NAME_IMAGES]'
            - '--image'
            - 'asia.gcr.io/[FIREBASE_PROJECT_ID]/[API_NAME_IMAGES]'
            - '--region'
            - 'asia-northeast1'
            - '--platform'
            - 'managed'
            - '--allow-unauthenticated'
images:
    - asia.gcr.io/[FIREBASE_PROJECT_ID]/[API_NAME_IMAGES]
